[tool.poetry]
name = "edtvelizy"
version = "0.1.0"
description = "API acting as a proxy between the services and the CELCAT application of the IUT of Vélizy"
authors = ["Yohann MARTIN <contact@codexus.fr>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.85.2"
ujson = "^5.5.0"
requests = "^2.28.1"
uvicorn = {extras = ["standard"], version = "^0.19.0"}
beautifulsoup4 = "^4.11.1"
redis = {extras = ["hiredis"], version = "^4.3.4"}


[tool.poetry.group.dev.dependencies]
flake8 = "^5.0.4"
black = "^22.10.0"
isort = "^5.10.1"
mypy = "^0.982"
types-requests = "^2.28.11.2"
types-ujson = "^5.5.0"
types-beautifulsoup4 = "^4.11.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.mypy]
plugins = "pydantic.mypy"
# --strict
disallow_any_generics = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
implicit_reexport = false
strict_equality = true
# --strict end

[[tool.mypy.overrides]]
module = [
]
ignore_missing_imports = true
